GET http://localhost:8080/notificationFCM?token=ef3bGfoE1BE:APA91bHYI-5V9Ehzp5mUKSd74B89TX9bbXT06JwOejsLXGU5CM4MrxmCWWU88LwlVrQ2T4pk1V2s0mOz8FLsyGILcRlekQN0CuJngQ2Cl9ce3XsDGyKhDqyS55UCSw-EJbmmAV_Uj5JW

###

GET http://localhost:8080/userList

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "username" : "Fanny"
}

> {%
client.global.set("id",response.body.id);
client.global.set("username",response.body.username);
client.global.set("type",response.body.type);
//client.global.set("pushToken",response.body.pushToken);
//client.global.set("imageUrl",response.body.imageUrl);
//client.global.set("connected",response.body.connected);
%}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "id" : "{{id}}",
  "username" : "{{username}}"
}

###

POST http://localhost:8080/position/register?userId={{id}}
Content-Type: application/json

{
    "latitude" : 45.293201302,
    "longitude" : 6.29302839
}

###
