GET http://localhost:8080/notificationFCM?token=fUfyI4VdjgU:APA91bGXGEWa8kDciZGpHyCacGodA6Y3EMOO4KYKkgxRjrR2wnmhtkBKyEqDv92dLhQbOt7V9K5vcmf11ZE5shm08AZlEkSSroFCM8oYHFQ-HL5GNw-w6fpmNt8qL0TotEPJ4vkv0J72

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "id" : "19f7c36a-35e9-41ff-8a72-0a75d6e3a5dc",
  "username" : "Fanny",
  "type" : "TEACHER"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "id" : "19f7c36a-35e9-41ff-8a72-0a75d6e3a5dc",
  "username" : "Fanny"
}

###

POST http://localhost:8080/position/register?userId=19f7c36a-35e9-41ff-8a72-0a75d6e3a5dc
Content-Type: application/json

{
    "latitude" : 45.293201302,
    "longitude" : 6.29302839
}

###
